In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('Homo_sapiens.GRCh38.107.gtf.gz',
                 sep ="\t", 
                 header = None, 
                 comment='#', 
                 compression='gzip')
df.head()

/var/folders/dk/dft1sb753rzdxzmxscz2nqf00000gn/T/ipykernel_1483/3810453286.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Homo_sapiens.GRCh38.107.gtf.gz',

,0,1,2,3,4,5,6,7,8
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
1,1,ensembl_havana,transcript,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
2,1,ensembl_havana,exon,1471765,1472089,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
3,1,ensembl_havana,CDS,1471885,1472089,.,+,0,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
4,1,ensembl_havana,start_codon,1471885,1471887,.,+,0,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."

In [5]:
df.columns = ['seqname', 'source', 'feature', 'start', 'end', 'score', 'strand', 'frame', 'group']

In [6]:
df

,seqname,source,feature,start,end,score,strand,frame,group
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
1,1,ensembl_havana,transcript,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
2,1,ensembl_havana,exon,1471765,1472089,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
3,1,ensembl_havana,CDS,1471885,1472089,.,+,0,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
4,1,ensembl_havana,start_codon,1471885,1471887,.,+,0,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
...,...,...,...,...,...,...,...,...,...
3371239,KI270713.1,ensembl,five_prime_utr,32373,32528,.,-,.,"gene_id ""ENSG00000277475""; gene_version ""1""; t..."
3371240,KI270713.1,ensembl,three_prime_utr,31698,31841,.,-,.,"gene_id ""ENSG00000277475""; gene_version ""1""; t..."
3371241,KI270713.1,ensembl,gene,21861,22024,.,-,.,"gene_id ""ENSG00000275405""; gene_version ""1""; g..."
3371242,KI270713.1,ensembl,transcript,21861,22024,.,-,.,"gene_id ""ENSG00000275405""; gene_version ""1""; t..."
3371243,KI270713.1,ensembl,exon,21861,22024,.,-,.,"gene_id ""ENSG00000275405""; gene_version ""1""; t..."

In [8]:
df["source"].value_counts()

havana                   2340968
ensembl_havana            714608
havana_tagene             170046
ensembl                   139551
mirbase                     5631
ensembl_havana_tagene        275
insdc                        144
ensembl_tagene                21
Name: source, dtype: int64

In [9]:
ens_df = df[df["df"].str.contains("ensembl_havana")].head()

KeyError: 'df'

In [13]:
ens_df = df.query("source == 'ensembl_havana'")

In [14]:
ens_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714608 entries, 0 to 3370048
Data columns (total 9 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   seqname  714608 non-null  object
 1   source   714608 non-null  object
 2   feature  714608 non-null  object
 3   start    714608 non-null  int64
 4   end      714608 non-null  int64
 5   score    714608 non-null  object
 6   strand   714608 non-null  object
 7   frame    714608 non-null  object
 8   group    714608 non-null  object
dtypes: int64(2), object(7)
memory usage: 54.5+ MB

In [12]:
df.info

<bound method DataFrame.info of             seqname          source          feature    start      end score  \
0                 1  ensembl_havana             gene  1471765  1497848     .
1                 1  ensembl_havana       transcript  1471765  1497848     .
2                 1  ensembl_havana             exon  1471765  1472089     .
3                 1  ensembl_havana              CDS  1471885  1472089     .
4                 1  ensembl_havana      start_codon  1471885  1471887     .
...             ...             ...              ...      ...      ...   ...
3371239  KI270713.1         ensembl   five_prime_utr    32373    32528     .
3371240  KI270713.1         ensembl  three_prime_utr    31698    31841     .
3371241  KI270713.1         ensembl             gene    21861    22024     .
3371242  KI270713.1         ensembl       transcript    21861    22024     .
3371243  KI270713.1         ensembl             exon    21861    22024     .

        strand frame                                              group
0            +     .  gene_id "ENSG00000160072"; gene_version "20"; ...
1            +     .  gene_id "ENSG00000160072"; gene_version "20"; ...
2            +     .  gene_id "ENSG00000160072"; gene_version "20"; ...
3            +     0  gene_id "ENSG00000160072"; gene_version "20"; ...
4            +     0  gene_id "ENSG00000160072"; gene_version "20"; ...
...        ...   ...                                                ...
3371239      -     .  gene_id "ENSG00000277475"; gene_version "1"; t...
3371240      -     .  gene_id "ENSG00000277475"; gene_version "1"; t...
3371241      -     .  gene_id "ENSG00000275405"; gene_version "1"; g...
3371242      -     .  gene_id "ENSG00000275405"; gene_version "1"; t...
3371243      -     .  gene_id "ENSG00000275405"; gene_version "1"; t...

[3371244 rows x 9 columns]>

In [15]:
ens_df_feature = ens_df.groupby("feature")

In [16]:
ens_df_feature

In [17]:
ens_df["feature"].value_counts()

exon               285809
CDS                262659
five_prime_utr      38184
three_prime_utr     30118
transcript          26745
stop_codon          25906
start_codon         25889
gene                19285
Selenocysteine         13
Name: feature, dtype: int64

In [18]:
genes = ens_df.query("feature == 'gene'")

In [19]:
genes

,seqname,source,feature,start,end,score,strand,frame,group
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
132,1,ensembl_havana,gene,3069168,3438621,.,+,.,"gene_id ""ENSG00000142611""; gene_version ""17""; ..."
361,1,ensembl_havana,gene,2403964,2413797,.,-,.,"gene_id ""ENSG00000157911""; gene_version ""11""; ..."
517,1,ensembl_havana,gene,2228319,2310213,.,+,.,"gene_id ""ENSG00000157933""; gene_version ""10""; ..."
580,1,ensembl_havana,gene,10472288,10630758,.,+,.,"gene_id ""ENSG00000142655""; gene_version ""13""; ..."
...,...,...,...,...,...,...,...,...,...
3365880,21,ensembl_havana,gene,6318378,6360415,.,+,.,"gene_id ""ENSG00000278903""; gene_version ""5""; g..."
3365953,21,ensembl_havana,gene,33915534,33977703,.,+,.,"gene_id ""ENSG00000237945""; gene_version ""9""; g..."
3367972,21,ensembl_havana,gene,9068325,9129773,.,-,.,"gene_id ""ENSG00000188681""; gene_version ""13""; ..."
3368345,21,ensembl_havana,gene,14236206,14362754,.,+,.,"gene_id ""ENSG00000243064""; gene_version ""10""; ..."
3369764,21,ensembl_havana,gene,46324124,46445769,.,+,.,"gene_id ""ENSG00000160299""; gene_version ""19""; ..."

In [20]:
genes['gene_length'] = df['end'] - df['start']

/var/folders/dk/dft1sb753rzdxzmxscz2nqf00000gn/T/ipykernel_1483/2396139549.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genes['gene_length'] = df['end'] - df['start']

In [21]:
genes

,seqname,source,feature,start,end,score,strand,frame,group,gene_length
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ...",26083
132,1,ensembl_havana,gene,3069168,3438621,.,+,.,"gene_id ""ENSG00000142611""; gene_version ""17""; ...",369453
361,1,ensembl_havana,gene,2403964,2413797,.,-,.,"gene_id ""ENSG00000157911""; gene_version ""11""; ...",9833
517,1,ensembl_havana,gene,2228319,2310213,.,+,.,"gene_id ""ENSG00000157933""; gene_version ""10""; ...",81894
580,1,ensembl_havana,gene,10472288,10630758,.,+,.,"gene_id ""ENSG00000142655""; gene_version ""13""; ...",158470
...,...,...,...,...,...,...,...,...,...,...
3365880,21,ensembl_havana,gene,6318378,6360415,.,+,.,"gene_id ""ENSG00000278903""; gene_version ""5""; g...",42037
3365953,21,ensembl_havana,gene,33915534,33977703,.,+,.,"gene_id ""ENSG00000237945""; gene_version ""9""; g...",62169
3367972,21,ensembl_havana,gene,9068325,9129773,.,-,.,"gene_id ""ENSG00000188681""; gene_version ""13""; ...",61448
3368345,21,ensembl_havana,gene,14236206,14362754,.,+,.,"gene_id ""ENSG00000243064""; gene_version ""10""; ...",126548
3369764,21,ensembl_havana,gene,46324124,46445769,.,+,.,"gene_id ""ENSG00000160299""; gene_version ""19""; ...",121645

In [29]:
genes["gene_length"].describe()

count    1.928500e+04
mean     6.767102e+04
std      1.298531e+05
min      6.200000e+01
25%      9.736000e+03
50%      2.736400e+04
75%      7.086500e+04
max      2.473538e+06
Name: gene_length, dtype: float64

In [39]:
sorted_genes = genes.sort_values(by=['gene_length'], ascending=False)

In [42]:
longest_genes = sorted_genes.iloc[0:10,:]

In [43]:
longest_genes

,seqname,source,feature,start,end,score,strand,frame,group,gene_length
2679474,16,ensembl_havana,gene,5239802,7713340,.,+,.,"gene_id ""ENSG00000078328""; gene_version ""23""; ...",2473538
1297140,7,ensembl_havana,gene,146116002,148420998,.,+,.,"gene_id ""ENSG00000174469""; gene_version ""23""; ...",2304996
1733179,9,ensembl_havana,gene,8314246,10613002,.,-,.,"gene_id ""ENSG00000153707""; gene_version ""19""; ...",2298756
1514121,X,ensembl_havana,gene,31097677,33339609,.,-,.,"gene_id ""ENSG00000198947""; gene_version ""18""; ...",2241932
1850816,11,ensembl_havana,gene,83455012,85627922,.,-,.,"gene_id ""ENSG00000150672""; gene_version ""18""; ...",2172910
1601567,8,ensembl_havana,gene,2935353,4994972,.,-,.,"gene_id ""ENSG00000183117""; gene_version ""20""; ...",2059619
3030998,20,ensembl_havana,gene,13995369,16053197,.,+,.,"gene_id ""ENSG00000172264""; gene_version ""18""; ...",2057828
1104549,6,ensembl_havana,gene,63719980,65707226,.,-,.,"gene_id ""ENSG00000188107""; gene_version ""15""; ...",1987246
2041854,10,ensembl_havana,gene,65912457,67763637,.,-,.,"gene_id ""ENSG00000183230""; gene_version ""18""; ...",1851180
2040306,10,ensembl_havana,gene,53802771,55627942,.,-,.,"gene_id ""ENSG00000150275""; gene_version ""20""; ...",1825171

In [45]:
sorted_genes_descending = genes.sort_values(by=['gene_length'], ascending=True)

In [46]:
sorted_genes_descending

,seqname,source,feature,start,end,score,strand,frame,group,gene_length
2913291,17,ensembl_havana,gene,43131208,43131270,.,+,.,"gene_id ""ENSG00000285057""; gene_version ""1""; g...",62
2118533,12,ensembl_havana,gene,93083598,93083675,.,-,.,"gene_id ""ENSG00000256393""; gene_version ""1""; g...",77
2362811,14,ensembl_havana,gene,22852616,22852728,.,-,.,"gene_id ""ENSG00000212335""; gene_version ""1""; g...",112
904441,4,ensembl_havana,gene,90838903,90839037,.,-,.,"gene_id ""ENSG00000187653""; gene_version ""11""; ...",134
1133423,6,ensembl_havana,gene,73373108,73373263,.,-,.,"gene_id ""ENSG00000235174""; gene_version ""1""; g...",155
...,...,...,...,...,...,...,...,...,...,...
1850816,11,ensembl_havana,gene,83455012,85627922,.,-,.,"gene_id ""ENSG00000150672""; gene_version ""18""; ...",2172910
1514121,X,ensembl_havana,gene,31097677,33339609,.,-,.,"gene_id ""ENSG00000198947""; gene_version ""18""; ...",2241932
1733179,9,ensembl_havana,gene,8314246,10613002,.,-,.,"gene_id ""ENSG00000153707""; gene_version ""19""; ...",2298756
1297140,7,ensembl_havana,gene,146116002,148420998,.,+,.,"gene_id ""ENSG00000174469""; gene_version ""23""; ...",2304996
2679474,16,ensembl_havana,gene,5239802,7713340,.,+,.,"gene_id ""ENSG00000078328""; gene_version ""23""; ...",2473538

In [47]:
shortest_genes = sorted_genes_descending.iloc[0:20,:]

In [48]:
shortest_genes

,seqname,source,feature,start,end,score,strand,frame,group,gene_length
2913291,17,ensembl_havana,gene,43131208,43131270,.,+,.,"gene_id ""ENSG00000285057""; gene_version ""1""; g...",62
2118533,12,ensembl_havana,gene,93083598,93083675,.,-,.,"gene_id ""ENSG00000256393""; gene_version ""1""; g...",77
2362811,14,ensembl_havana,gene,22852616,22852728,.,-,.,"gene_id ""ENSG00000212335""; gene_version ""1""; g...",112
904441,4,ensembl_havana,gene,90838903,90839037,.,-,.,"gene_id ""ENSG00000187653""; gene_version ""11""; ...",134
1133423,6,ensembl_havana,gene,73373108,73373263,.,-,.,"gene_id ""ENSG00000235174""; gene_version ""1""; g...",155
129959,1,ensembl_havana,gene,27649419,27649610,.,+,.,"gene_id ""ENSG00000235912""; gene_version ""1""; g...",191
1847776,11,ensembl_havana,gene,82689559,82689768,.,+,.,"gene_id ""ENSG00000227097""; gene_version ""5""; g...",209
2938518,18,ensembl_havana,gene,52409042,52409257,.,+,.,"gene_id ""ENSG00000280098""; gene_version ""1""; g...",215
675285,3,ensembl_havana,gene,186596976,186597200,.,+,.,"gene_id ""ENSG00000283390""; gene_version ""1""; g...",224
988497,5,ensembl_havana,gene,62512246,62512482,.,-,.,"gene_id ""ENSG00000268942""; gene_version ""2""; g...",236
1967063,10,ensembl_havana,gene,29697935,29698174,.,+,.,"gene_id ""ENSG00000225976""; gene_version ""5""; g...",239
3255568,Y,ensembl_havana,gene,18992467,18992709,.,-,.,"gene_id ""ENSG00000185275""; gene_version ""6""; g...",242
3363759,21,ensembl_havana,gene,30718525,30718777,.,-,.,"gene_id ""ENSG00000231068""; gene_version ""1""; g...",252
2274799,12,ensembl_havana,gene,3211663,3211917,.,-,.,"gene_id ""ENSG00000227081""; gene_version ""5""; g...",254
1268412,7,ensembl_havana,gene,129410113,129410370,.,-,.,"gene_id ""ENSG00000238072""; gene_version ""1""; g...",257
105987,1,ensembl_havana,gene,152622834,152623103,.,-,.,"gene_id ""ENSG00000185962""; gene_version ""1""; g...",269
2594158,16,ensembl_havana,gene,26032539,26032811,.,-,.,"gene_id ""ENSG00000230330""; gene_version ""1""; g...",272
2526556,15,ensembl_havana,gene,29730713,29730985,.,+,.,"gene_id ""ENSG00000234664""; gene_version ""1""; g...",272
3363751,21,ensembl_havana,gene,30642864,30643136,.,+,.,"gene_id ""ENSG00000206104""; gene_version ""2""; g...",272
3363727,21,ensembl_havana,gene,30616425,30616699,.,+,.,"gene_id ""ENSG00000244624""; gene_version ""3""; g...",274

In [49]:
split_group = genes["group"].str.split(";").to_frame().head()

In [50]:
split_group

                                                 group
0    [gene_id "ENSG00000160072",  gene_version "20"...
132  [gene_id "ENSG00000142611",  gene_version "17"...
361  [gene_id "ENSG00000157911",  gene_version "11"...
517  [gene_id "ENSG00000157933",  gene_version "10"...
580  [gene_id "ENSG00000142655",  gene_version "13"...

In [51]:
ens_df.merge(split_group, on="group", how="inner")

TypeError: unhashable type: 'list'

In [52]:
genes_per_chr = genes.groupby("seqname")

In [53]:
genes_per_chr

In [54]:
genes_per_chr.describe()

          start                                                       \
          count          mean           std         min          25%
seqname
1        2009.0  1.128017e+08  7.632351e+07     65419.0  36466043.00
2        1222.0  1.249662e+08  7.387081e+07     38814.0  64182981.25
3        1040.0  9.710336e+07  5.892302e+07    196763.0  47007237.50
4         736.0  8.588778e+07  5.733972e+07     53286.0  39488817.25
5         835.0  1.096735e+08  5.281069e+07     92168.0  69178354.50
6         995.0  6.950979e+07  4.953143e+07    131910.0  31150493.00
7         804.0  8.459091e+07  4.757134e+07    192571.0  43067565.75
8         304.0  6.481184e+07  4.872622e+07    166086.0  22344287.50
9         752.0  9.028893e+07  4.346695e+07     14475.0  38600497.25
10        725.0  7.515648e+07  3.793313e+07     46888.0  45972489.00
11       1261.0  6.147474e+07  3.922904e+07    112967.0  28108248.00
12        998.0  6.280751e+07  4.025189e+07     66767.0  27361311.00
13        319.0  5.972681e+07  3.144025e+07  18408806.0  33059780.00
14        616.0  6.112675e+07  2.932076e+07  18601117.0  30313488.25
15        577.0  6.066787e+07  2.111246e+07  20562375.0  42348103.00
16        823.0  3.951028e+07  3.014854e+07     46407.0  11097079.00
17       1138.0  4.070888e+07  2.490666e+07    137569.0  18230430.00
18        265.0  3.948244e+07  2.395232e+07     47221.0  15056845.00
19       1122.0  3.028500e+07  1.930766e+07    107104.0  11543918.75
20        536.0  3.466741e+07  1.990573e+07     87250.0  18812769.25
21         70.0  2.901048e+07  1.007805e+07   5553637.0  25599056.50
22        361.0  3.244761e+07  9.997649e+06  15528192.0  23179704.00
19        240.0  3.389139e+07  1.828087e+07    812488.0  17783050.50
21        147.0  3.477356e+07  1.194907e+07   5022531.0  30765611.00
22         91.0  3.752528e+07  8.779680e+06  16590751.0  31303699.00
7          71.0  7.743717e+07  4.532863e+07    497258.0  38360688.00
8         356.0  7.896998e+07  4.495036e+07    406428.0  40294064.75
X         811.0  8.470459e+07  4.792873e+07    276322.0  48067481.00
Y          61.0  1.680047e+07  7.230866e+06   2786855.0   9527880.00

                                                    end                ...  \
                 50%           75%          max   count          mean  ...
seqname                                                                ...
1        113390515.0  1.691325e+08  248906196.0  2009.0  1.128589e+08  ...
2        113083642.5  1.975551e+08  241869600.0  1222.0  1.250528e+08  ...
3        100447075.5  1.461002e+08  197960200.0  1040.0  9.719733e+07  ...
4         80301184.5  1.376802e+08  190173774.0   736.0  8.598419e+07  ...
5        129748094.0  1.502579e+08  181367268.0   835.0  1.097591e+08  ...
6         44000580.0  1.131023e+08  170575295.0   995.0  6.958302e+07  ...
7         95678002.5  1.284611e+08  159028175.0   804.0  8.467858e+07  ...
8         42356258.5  1.044369e+08  144930358.0   304.0  6.489234e+07  ...
9        104299261.5  1.283815e+08  137877782.0   752.0  9.036051e+07  ...
10        80271820.0  1.026445e+08  133683668.0   725.0  7.524120e+07  ...
11        63079940.0  8.971030e+07  134378504.0  1261.0  6.152638e+07  ...
12        55832520.5  1.029275e+08  133218312.0   998.0  6.287369e+07  ...
13        49247925.0  9.486473e+07  114314482.0   319.0  5.983173e+07  ...
14        63923065.5  9.011063e+07  106874583.0   616.0  6.119391e+07  ...
15        63321378.0  7.710066e+07  101922042.0   577.0  6.074582e+07  ...
16        30698209.0  6.788907e+07   90173217.0   823.0  3.955786e+07  ...
17        41311306.0  5.988465e+07   83079609.0  1138.0  4.074930e+07  ...
18        37243040.0  5.926704e+07   80157232.0   265.0  3.959190e+07  ...
19        35746980.5  4.883108e+07   58561931.0  1122.0  3.030948e+07  ...
20        36271233.5  4.928198e+07   64290385.0   536.0  3.472166e+07  ...
21        30980072.5  3.611879e+07   46598604.0    70.0  2.910594e+07  ...
22        31618491.0  3.952909e+07   50767501.0   361.0  3.248780e+07  ...
19        40251903.0  4.806474e+07   57977076.0   240.0  3.391647e+07  ...
21        39342315.0  4.382737e+07   46635595.0   147.0  3.482753e+07  ...
22        39743044.0  4.479170e+07   50343304.0    91.0  3.759145e+07  ...
7         87322943.0  1.075721e+08  156388922.0    71.0  7.753937e+07  ...
8         78591214.5  1.203969e+08  145052465.0   356.0  7.906666e+07  ...
X         78945332.0  1.298547e+08  156020826.0   811.0  8.477032e+07  ...
Y         18772706.0  2.297382e+07   25975549.0    61.0  1.685450e+07  ...

                                   gene_length                                \
                  75%          max       count           mean            std
seqname
1        1.693679e+08  248919946.0      2009.0   57141.112992  107043.255133
2        1.976455e+08  241873823.0      1222.0   86600.607201  139473.259443
3        1.461855e+08  198043720.0      1040.0   93965.008654  171439.552392
4        1.377100e+08  190185942.0       736.0   96408.373641  154822.552760
5        1.503147e+08  181368262.0       835.0   85639.657485  128743.813319
6        1.131074e+08  170584692.0       995.0   73231.225126  136261.985072
7        1.284705e+08  159144867.0       804.0   87677.218905  167218.151568
8        1.044976e+08  144950888.0       304.0   80495.348684  178037.347733
9        1.284033e+08  138124624.0       752.0   71571.687500  140419.868119
10       1.026583e+08  133684936.0       725.0   84721.099310  155353.760367
11       8.971787e+07  134412242.0      1261.0   51645.394132  123045.798674
12       1.029600e+08  133235877.0       998.0   66181.471944  109277.089171
13       9.500701e+07  114337626.0       319.0  104916.489028  171387.751752
14       9.020825e+07  106875071.0       616.0   67166.748377  125914.150080
15       7.742014e+07  101923113.0       577.0   77954.305026  111304.550321
16       6.790927e+07   90222851.0       823.0   47577.639125  118305.706859
17       5.993617e+07   83095122.0      1138.0   40418.720562   75646.899374
18       5.927409e+07   80247514.0       265.0  109459.656604  148031.437933
19       4.886059e+07   58573575.0      1122.0   24486.719251   33383.796074
20       4.934577e+07   64313132.0       536.0   54251.886194  125214.452212
21       3.612821e+07   46605208.0        70.0   95460.300000  177068.179267
22       3.953276e+07   50801309.0       361.0   40188.700831   70611.924513
19       4.812576e+07   58003349.0       240.0   25084.708333   24626.483113
21       4.389644e+07   46665124.0       147.0   53972.210884   90592.560662
22       4.493636e+07   50445090.0        91.0   66167.461538   89383.026598
7        1.076262e+08  156640654.0        71.0  102202.507042  181652.537774
8        1.204696e+08  145066685.0       356.0   96684.362360  150044.306593
X        1.298868e+08  156025710.0       811.0   65726.053021  145339.541124
Y        2.300546e+07   25988069.0        61.0   54031.918033  117153.357329


            min       25%      50%        75%        max
seqname
1         191.0   9072.00  24448.0   58905.00  1551956.0
2         313.0  14108.50  43435.0  101049.25  1463630.0
3         224.0  14727.50  41582.5   93488.50  1743269.0
4         134.0  16185.75  48647.0  112178.75  1506191.0
5         236.0  14679.00  43041.0  102746.50  1553082.0
6         155.0   9442.00  25999.0   79145.50  1987246.0
7         257.0  12206.00  32601.0   86587.50  2304996.0
8         662.0   9758.25  29936.0   77911.25  2059619.0
9         341.0   7955.00  27983.0   84100.75  2298756.0
10        239.0  14789.00  38975.0   90568.00  1851180.0
11        209.0   6022.00  16346.0   47649.00  2172910.0
12         77.0  10998.75  29043.5   71513.00  1258479.0
13        398.0  19597.50  46371.0  112931.50  1475061.0
14        112.0   8988.75  25254.0   77939.25  1697918.0
15        272.0  15130.00  38526.0   97223.00   969298.0
16        272.0   7688.00  19768.0   51933.50  2473538.0
17         62.0   7108.00  17021.5   43190.75  1161877.0
18        215.0  26960.00  52441.0  137560.00  1195706.0
19        741.0   7882.25  15428.0   29851.25   485248.0
20        305.0   9654.25  23600.5   57606.00  2057828.0
21        369.0  15188.75  38115.5   87553.00  1216866.0
22        476.0   9252.00  20297.0   41999.00   760615.0
19        838.0   8399.25  16572.5   33944.25   144080.0
21        252.0   8047.00  27325.0   65406.00   836159.0
22       1379.0  11442.00  32987.0   83496.50   550561.0
7         650.0  18552.00  39586.0  113986.00  1195210.0
8         347.0  13074.75  44002.5  116458.75  1214011.0
X         347.0   5930.00  19277.0   66260.00  2241932.0
Y         242.0   2814.00  14471.0   42272.00   741998.0

[29 rows x 24 columns]